name: Extract M3U8 Link and Record Video

on:
  workflow_dispatch:

jobs:
  run-puppeteer-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      # Naya package 'puppeteer-screen-recorder' install karna zaroori hai
      - name: Install Dependencies
        run: npm install puppeteer puppeteer-screen-recorder fs path

      - name: Run Extraction Code
        run: node extract.js

      # Step 5: Videos folder ko Artifacts mein upload karna
      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-video-record
          path: videos/ # Videos folder upload karega
          retention-days: 5 # Video 5 din tak GitHub par save rahegi
